import {IconDefinition} from "@fortawesome/free-brands-svg-icons";
import {faAirbnb} from "@fortawesome/free-brands-svg-icons/faAirbnb";
import {faTimes} from "@fortawesome/free-solid-svg-icons/faTimes";
import {
  faBan,
  faBars,
  faBox,
  faChampagneGlasses,
  faChessRook,
  faCircle,
  faCircleNotch,
  faDollarSign,
  faEarthEurope,
  faExclamation,
  faEye,
  faFire,
  faHillRockslide,
  faHouse,
  faKitchenSet,
  faLightbulb,
  faMinus,
  faMugSaucer,
  faPersonSkiing,
  faPlus,
  faSailboat,
  faSearch, faSnowflake, faTent, faTowerObservation,
  faTractor, faTrashCan, faTree, faUmbrellaBeach,
  faUser, faWater
} from "@fortawesome/free-solid-svg-icons";

export let fontAwesomeIcons: IconDefinition[];
fontAwesomeIcons = [
  //faAirbnb,faTimes,faUser, faSearch, faBars,faEye
  faBan,
  faBars,
  faBox,
  faChampagneGlasses,
  faChessRook,
  faCircle,
  faCircleNotch,
  faDollarSign,
  faEarthEurope,
  faExclamation,
  faEye,
  faHillRockslide,
  faHouse,
  faKitchenSet,
  faMinus,
  faLightbulb,
  faFire,
  faMugSaucer,
  faPersonSkiing,
  faPlus,
  faSailboat,
  faSearch,
  faSnowflake,
  faTent,
  faTowerObservation,
  faTractor,
  faTrashCan,
  faTree,
  faUmbrellaBeach,
  faUser,
  faWater,
  faAirbnb
];
